# Generated by Django 5.1.1 on 2024-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demokratietag_Derksen', '0002_alter_person_entry_time_alter_person_exit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='verbleibende_zeit',
            field=models.DurationField(null=True),
        ),
    ]
