# Generated by Django 5.1.1 on 2024-10-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demokratietag_Derksen', '0004_alter_person_verbleibende_zeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(null=True),
        ),
    ]
