# Generated by Django 5.0.1 on 2024-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demokratietag_Derksen', '0005_person_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='anreise',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='anzahl',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='brotzeit',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='completename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='dinge',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='getraenk',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='handy',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='in_or_out',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='person',
            name='klasse',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='lehrer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='projekt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='raum',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='thiersee',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='entry_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='exit_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='verbleibende_zeit',
            field=models.CharField(default='', max_length=255),
        ),
    ]
